FROM nginx:1.22
RUN apt-get update && apt-get install -y init nano curl net-tools telnet 
RUN curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh | bash
RUN curl -O https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-dat-release.sh
RUN bash install-dat-release.sh
RUN systemctl enable xray

COPY nginx.conf /etc/nginx/nginx.conf
COPY config.json /usr/local/etc/xray/config.json

CMD service nginx start && /usr/local/bin/xray run -config /usr/local/etc/xray/config.json
